source("http://bioconductor.org/biocLite.R")
#biocLite("DESeq")
#biocLite("metagenomeSeq")
library(DESeq)
library(metagenomeSeq)
library(ggplot2)
library(COUNT)
library(gmodels)

vignette("metagenomeSeq")
